variables:

  SKIP_MAIN_BUILD: 1
  SKIP_BRANCH_BUILD: 1

  FRONTEND_PACKAGE_MANAGER: npm
  FRONTEND_BUILD_IMAGE: registry.awesome-it.de/upstream-dockerhub/library/node:20-alpine
  FRONTEND_PACKAGE_PUBLISH: 1
  FRONTEND_PACKAGE_PUBLISH_NPMJS: 1
  FRONTEND_PACKAGE_SCOPE: "@awesome-it"
  FRONTEND_PACKAGE_REGISTRY_URL: https://registry.npmjs.org

include:
  - project: awesome/cicd
    file: common.yml
    ref: v1.0
  - project: awesome/cicd
    file: frontend.yml
    ref: v1.0
