variables:

  SKIP_MAIN_BUILD: 1
  SKIP_BRANCH_BUILD: 1

  FRONTEND_PACKAGE_MANAGER: yarn
  FRONTEND_BUILD_IMAGE: registry.awesome-it.de/upstream-dockerhub/library/node:20-alpine
  FRONTEND_PACKAGE_PUBLISH: 1

include:
  - project: awesome/cicd
    file: common.yml
    ref: v1.0
  - project: awesome/cicd
    file: frontend.yml
    ref: v1.0
